### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by addmix** [VP-GAMES/Godot4QuestEditor#4]
There is no documentation of how to actually use these plugins. After digging through the code I found that to create a trigger, you must drag your trigger's .tscn file onto this little icon, any other method and it does not work. Please at least showcase a video of creating a basic quest, trigger, localization, and dialogue.
![image](https://github.com/VP-GAMES/Godot4QuestEditor/assets/38119387/3c1d21f8-1e10-4fce-8fa9-512ab58e568d)

**Comment by BrokedArrer** [comment]
This system is so broken its crazy. If you ONLY want the quest system good luck... Your best bet it to just re-write his code for the parts you actually want into your own game. This systems crap cause you cant install quest without all the other addons getting added, and when you remove them quests are broken XD Garbage.

**Comment by VP-GAMES** [comment]
I created this quest plugin based on other plugins. It was so planed. You can use separately LocalizationEditor, InventoryEditor and DialogueEditor. But QuestEditor only works with other Plug-ins together. I use this QuestEditor in my game. It works wery well. I have just no time to make documentation for QuestEditor, but it's really easy to use. Please look at examples integrated in Plug-in.
